import { ActivityDto, ActivityFeedbackDto, StageContentDto } from '../../../../core/models/activity.models';

export function makeStageContent(overrides: Partial<StageContentDto> = {}): StageContentDto {
  return {
    schemaVersion: 'module_stage_v1',
    learn: {
      teachingTitle: 'Listening for action and deadline',
      explanation: 'Listen for the main idea, the action requested, and any deadline.',
      keyPoints: ['Focus on verbs', 'Note any dates or times'],
      examples: [{ phrase: 'by end of day', meaning: 'before today finishes', note: 'common deadline phrase' }],
      strategy: 'Listen for who, what, and when.',
      commonMistakes: ['Missing the deadline'],
      sourceLanguageSupport: null,
    },
    practice: {
      instructions: 'Listen and answer the questions.',
      scenario: 'A colleague leaves a voicemail.',
      task: null,
      exerciseData: {},
    },
    feedbackPlan: {
      evaluationCriteria: ['Main idea understood'],
      rubric: [],
      feedbackFocus: 'Main idea and deadline',
      successCriteria: [],
    },
    ...overrides,
  };
}

export function makeActivity(overrides: Partial<ActivityDto> = {}): ActivityDto {
  return {
    activityId: 'a1',
    activityType: 'writingScenario',
    source: 'aiGenerated',
    title: 'Title',
    difficulty: 'B1',
    situation: null,
    learningGoal: null,
    targetPhrases: [],
    targetVocabulary: [],
    exampleText: null,
    commonMistakeToAvoid: null,
    instructionInSourceLanguage: null,
    instructions: null,
    practiceMode: null,
    vocabItems: null,
    scenario: null,
    speakerRole: null,
    listenerRole: null,
    transcriptAvailableAfterSubmit: null,
    listeningQuestions: null,
    responseTask: null,
    audioAvailable: null,
    audioUrl: null,
    audioContentType: null,
    audioDurationSeconds: null,
    audioUnavailableMessage: null,
    audioStatus: null,
    speakingScenario: null,
    studentRole: null,
    speakingListenerRole: null,
    speakingGoal: null,
    speakingPrompt: null,
    expectedPoints: null,
    suggestedPhrases: null,
    maxDurationSeconds: null,
    interactionMode: null,
    exercisePatternKey: null,
    contentJson: null,
    stageContent: null,
    ...overrides,
  };
}

export function makeFeedback(overrides: Partial<ActivityFeedbackDto> = {}): ActivityFeedbackDto {
  return {
    attemptId: 'attempt1',
    score: 80,
    coachSummary: null,
    focusFirst: false,
    changes: [],
    correctedText: null,
    whatYouDidWell: [],
    mainMistakes: [],
    grammarIssues: [],
    vocabularyIssues: [],
    toneIssues: [],
    clarityIssues: [],
    grammarExplanation: null,
    toneExplanation: null,
    vocabularyToRemember: [],
    miniLesson: null,
    nextImprovementStep: null,
    rewriteChallenge: null,
    nextPracticeSuggestion: null,
    feedbackInSourceLanguage: null,
    questionFeedback: null,
    transcript: null,
    responseFeedback: null,
    speakingStrengths: null,
    speakingImprovements: null,
    missingExpectedPoints: null,
    suggestedImprovedResponse: null,
    patternEvaluation: null,
    ...overrides,
  };
}

