import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { AdminImportPackageService } from '../../../core/services/admin-import-package.service';
import { ImportExecutionPlanDto, ImportPackageManifestSummaryDto } from '../../../core/models/admin-import-package.models';
import {
  SpAdminAlertComponent,
  SpAdminBadgeComponent,
  SpAdminButtonComponent,
  SpAdminErrorStateComponent,
  SpAdminFormFieldComponent,
  SpAdminInputComponent,
  SpAdminLoadingStateComponent,
  SpAdminModalComponent,
  SpAdminPageBodyComponent,
  SpAdminPageHeaderComponent,
  SpAdminSectionCardComponent,
  SpAdminTextareaComponent,
} from '../../../design-system/admin';

/**
 * Mandatory Import Execution Plan addendum (2026-07-15) — /admin/content/import/packages/:packageId/plan.
 * Every package (regardless of size) must reach this page before any AI/STT/TTS/background
 * processing begins: it shows the automatically-generated plan (detected structure, proposed
 * decisions, volume/time/cost estimate, risks) and requires an explicit "Approve and Start
 * Processing" action with an admin-set cost ceiling. No pre-checked approval, no implicit start.
 */
@Component({
  selector: 'app-admin-import-package-plan',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    SpAdminAlertComponent,
    SpAdminBadgeComponent,
    SpAdminButtonComponent,
    SpAdminErrorStateComponent,
    SpAdminFormFieldComponent,
    SpAdminInputComponent,
    SpAdminLoadingStateComponent,
    SpAdminModalComponent,
    SpAdminPageBodyComponent,
    SpAdminPageHeaderComponent,
    SpAdminSectionCardComponent,
    SpAdminTextareaComponent,
  ],
  templateUrl: './admin-import-package-plan.component.html',
})
export class AdminImportPackagePlanComponent implements OnInit {
  packageId = '';

  loading = signal(true);
  error = signal('');

  manifest = signal<ImportPackageManifestSummaryDto | null>(null);
  plan = signal<ImportExecutionPlanDto | null>(null);

  regenerating = signal(false);

  approveModalOpen = signal(false);
  approvedCostCeiling: number | null = null;
  approving = signal(false);
  approveError = signal('');

  rejectModalOpen = signal(false);
  rejectReason = '';
  rejecting = signal(false);
  rejectError = signal('');

  resumeModalOpen = signal(false);
  resumeCostCeiling: number | null = null;
  resuming = signal(false);
  resumeError = signal('');

  constructor(
    private packageSvc: AdminImportPackageService,
    private route: ActivatedRoute,
    private router: Router,
  ) {}

  ngOnInit(): void {
    this.packageId = this.route.snapshot.paramMap.get('packageId') ?? '';
    if (!this.packageId) {
      this.error.set('No package id in the route.');
      this.loading.set(false);
      return;
    }
    this.load();
  }

  load(): void {
    this.loading.set(true);
    this.error.set('');
    this.packageSvc.getManifest(this.packageId).subscribe({
      next: manifest => {
        this.manifest.set(manifest);
        this.packageSvc.getPlan(this.packageId).subscribe({
          next: plan => { this.plan.set(plan); this.loading.set(false); },
          error: () => { this.plan.set(null); this.loading.set(false); },
        });
      },
      error: err => {
        this.error.set(err.error?.error ?? 'Could not load this package.');
        this.loading.set(false);
      },
    });
  }

  /** Sample selection and structure analysis are fully automatic — there is no manual sample
   *  picker here. This button re-runs that same automatic process (e.g. after the archive
   *  contents were corrected upstream). */
  generatePlan(): void {
    this.regenerating.set(true);
    this.error.set('');
    const changeReason = this.plan() ? 'Regenerated by administrator from the Import Plan page.' : undefined;
    this.packageSvc.generatePlan(this.packageId, changeReason).subscribe({
      next: plan => { this.plan.set(plan); this.regenerating.set(false); },
      error: err => {
        this.error.set(err.error?.error ?? 'Could not generate an Import Execution Plan.');
        this.regenerating.set(false);
      },
    });
  }

  openApprove(): void {
    this.approveError.set('');
    this.approvedCostCeiling = this.plan()?.estimate?.cost?.maxCost ?? null;
    this.approveModalOpen.set(true);
  }

  confirmApprove(): void {
    const plan = this.plan();
    if (!plan || this.approvedCostCeiling === null || this.approvedCostCeiling < 0) {
      this.approveError.set('An approved cost ceiling (>= 0) is required.');
      return;
    }
    this.approving.set(true);
    this.approveError.set('');
    this.packageSvc.approvePlan(this.packageId, plan.planId, this.approvedCostCeiling).subscribe({
      next: updated => {
        this.plan.set(updated);
        this.approving.set(false);
        this.approveModalOpen.set(false);
      },
      error: err => {
        const reasons: string[] | undefined = err.error?.blockingReasons;
        this.approveError.set(reasons?.length ? reasons.join(' ') : (err.error?.error ?? 'Could not approve this plan.'));
        this.approving.set(false);
      },
    });
  }

  openReject(): void {
    this.rejectReason = '';
    this.rejectError.set('');
    this.rejectModalOpen.set(true);
  }

  confirmReject(): void {
    const plan = this.plan();
    if (!plan || !this.rejectReason.trim()) {
      this.rejectError.set('A rejection reason is required.');
      return;
    }
    this.rejecting.set(true);
    this.rejectError.set('');
    this.packageSvc.rejectPlan(this.packageId, plan.planId, this.rejectReason.trim()).subscribe({
      next: updated => {
        this.plan.set(updated);
        this.rejecting.set(false);
        this.rejectModalOpen.set(false);
      },
      error: err => {
        this.rejectError.set(err.error?.error ?? 'Could not reject this plan.');
        this.rejecting.set(false);
      },
    });
  }

  openResume(): void {
    this.resumeCostCeiling = this.plan()?.approvedCostCeiling ?? null;
    this.resumeError.set('');
    this.resumeModalOpen.set(true);
  }

  confirmResume(): void {
    const plan = this.plan();
    if (!plan || this.resumeCostCeiling === null || this.resumeCostCeiling < 0) {
      this.resumeError.set('A revised cost ceiling (>= 0) is required.');
      return;
    }
    this.resuming.set(true);
    this.resumeError.set('');
    this.packageSvc.approveRevisedCeiling(this.packageId, plan.planId, this.resumeCostCeiling).subscribe({
      next: updated => {
        this.plan.set(updated);
        this.resuming.set(false);
        this.resumeModalOpen.set(false);
      },
      error: err => {
        this.resumeError.set(err.error?.error ?? 'Could not resume this plan.');
        this.resuming.set(false);
      },
    });
  }

  statusTone(status: string): 'neutral' | 'success' | 'warning' | 'danger' {
    switch (status) {
      case 'Approved': case 'Completed': return 'success';
      case 'AwaitingApproval': case 'Executing': return 'neutral';
      case 'PausedForCostApproval': return 'warning';
      case 'Rejected': case 'Failed': case 'Cancelled': case 'Superseded': return 'danger';
      default: return 'neutral';
    }
  }

  backToImport(): void {
    this.router.navigate(['/admin/content/import']);
  }
}
