using LinguaCoach.Domain.Entities;

namespace LinguaCoach.Infrastructure.LearningPath;

/// <summary>
/// Creates a safe hard-coded 5-module Workplace English path used when AI path generation fails.
/// No AI call — always succeeds.
/// </summary>
public static class DefaultPathFactory
{
    private static readonly (string Title, string Description)[] Modules =
    [
        ("Everyday communication essentials",  "Practice clear, polite English for common real-life situations: requests, follow-ups, and giving information."),
        ("Spoken clarity and confidence",      "Build confidence speaking English in conversations — asking questions, responding naturally, and summarising what you heard."),
        ("Reading and understanding texts",    "Practice reading real-life texts like notices, messages, and short documents, and answering questions about them."),
        ("Writing for real-life situations",   "Learn how to write short messages, requests, and updates clearly and with the right tone for your audience."),
        ("Building communication fluency",     "Practice the everyday English that builds relationships and helps you communicate comfortably in any context."),
    ];

    public static global::LinguaCoach.Domain.Entities.LearningPath Create(
        Guid studentProfileId,
        string careerContext,
        string cefrLevel)
    {
        var title = $"English for {careerContext} — {cefrLevel}";
        var path = new global::LinguaCoach.Domain.Entities.LearningPath(
            studentProfileId,
            title,
            learnerContextSummary: $"Default path for {careerContext} at {cefrLevel}. Generated by system fallback.");

        return path;
    }

    public static IReadOnlyList<LearningModule> CreateModules(Guid pathId)
    {
        return Modules
            .Select((m, i) => new LearningModule(pathId, m.Title, m.Description, order: i + 1))
            .ToList();
    }
}
