using LinguaCoach.Domain.Entities;

namespace LinguaCoach.Infrastructure.LearningPath;

/// <summary>
/// Creates a safe hard-coded 5-module Workplace English path used when AI path generation fails.
/// No AI call — always succeeds.
/// </summary>
public static class DefaultPathFactory
{
    private static readonly (string Title, string Description)[] Modules =
    [
        ("Professional email writing",        "Practice writing clear, polite workplace emails for common situations like follow-ups, requests, and status updates."),
        ("Meetings and spoken communication", "Build confidence for participating in workplace meetings, asking questions, and summarising action items."),
        ("Document control communication",   "Practice the specific language used in document control: transmittals, revision requests, approval follow-ups, and register updates."),
        ("Formal requests and approvals",     "Learn how to write and respond to formal requests, approvals, and escalations in a professional tone."),
        ("Workplace relationship building",   "Practice the everyday communication that builds professional relationships: greetings, small talk, and courteous follow-through."),
    ];

    public static global::LinguaCoach.Domain.Entities.LearningPath Create(
        Guid studentProfileId,
        string careerContext,
        string cefrLevel)
    {
        var title = $"Workplace English for {careerContext} — {cefrLevel}";
        var path = new global::LinguaCoach.Domain.Entities.LearningPath(
            studentProfileId,
            title,
            learnerContextSummary: $"Default path for {careerContext} at {cefrLevel}. Generated by system fallback.");

        return path;
    }

    public static IReadOnlyList<LearningModule> CreateModules(Guid pathId)
    {
        return Modules
            .Select((m, i) => new LearningModule(pathId, m.Title, m.Description, order: i + 1))
            .ToList();
    }
}
