import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { AdminModuleService } from '../../../core/services/admin-module.service';
import { ModuleDto } from '../../../core/models/admin-module.models';
import {
  SpAdminAlertComponent,
  SpAdminButtonComponent,
  SpAdminErrorStateComponent,
  SpAdminFormFieldComponent,
  SpAdminInputComponent,
  SpAdminLoadingStateComponent,
  SpAdminNumberInputComponent,
  SpAdminPageBodyComponent,
  SpAdminPageHeaderComponent,
  SpAdminSectionCardComponent,
  SpAdminTextareaComponent,
} from '../../../design-system/admin';

function parseJsonArray(json: string | null | undefined): string[] {
  if (!json) return [];
  try {
    const parsed = JSON.parse(json);
    return Array.isArray(parsed) ? parsed.filter(v => typeof v === 'string') : [];
  } catch {
    return [];
  }
}

/**
 * Phase K5 — Module edit as its own routed page (/admin/modules/:id/edit), replacing the earlier
 * in-place modal. Modules are now always auto-generated by the Module auto-link flow, so this is
 * the only way to correct a title/description/tags after the fact.
 */
@Component({
  selector: 'app-admin-module-edit',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    SpAdminAlertComponent,
    SpAdminButtonComponent,
    SpAdminErrorStateComponent,
    SpAdminFormFieldComponent,
    SpAdminInputComponent,
    SpAdminLoadingStateComponent,
    SpAdminNumberInputComponent,
    SpAdminPageBodyComponent,
    SpAdminPageHeaderComponent,
    SpAdminSectionCardComponent,
    SpAdminTextareaComponent,
  ],
  templateUrl: './admin-module-edit.component.html',
})
export class AdminModuleEditComponent implements OnInit {
  itemId = '';
  loading = signal(true);
  saving = signal(false);
  error = signal('');
  item: ModuleDto | null = null;

  title = '';
  description = '';
  cefrLevel = '';
  skill = '';
  subskill = '';
  contextTagsDraft = '';
  focusTagsDraft = '';
  difficultyBand: number | null = null;
  estimatedMinutes: number | null = null;

  constructor(
    private moduleSvc: AdminModuleService,
    private route: ActivatedRoute,
    private router: Router,
  ) {}

  ngOnInit(): void {
    this.itemId = this.route.snapshot.paramMap.get('id') ?? '';
    if (!this.itemId) return;
    this.load();
  }

  load(): void {
    this.loading.set(true);
    this.error.set('');
    this.moduleSvc.get(this.itemId).subscribe({
      next: item => {
        this.loading.set(false);
        this.item = item;
        this.title = item.title;
        this.description = item.description ?? '';
        this.cefrLevel = item.cefrLevel ?? '';
        this.skill = item.skill ?? '';
        this.subskill = item.subskill ?? '';
        this.contextTagsDraft = parseJsonArray(item.contextTagsJson).join(', ');
        this.focusTagsDraft = parseJsonArray(item.focusTagsJson).join(', ');
        this.difficultyBand = item.difficultyBand;
        this.estimatedMinutes = item.estimatedMinutes;
      },
      error: err => { this.loading.set(false); this.error.set(err.error?.error ?? 'Could not load this Module for editing.'); },
    });
  }

  cancel(): void {
    this.router.navigateByUrl(`/admin/modules/${this.itemId}`);
  }

  private parseTags(raw: string): string[] {
    return raw.split(',').map(t => t.trim()).filter(t => t.length > 0);
  }

  save(): void {
    if (!this.item) return;
    if (!this.title.trim()) {
      this.error.set('Title is required.');
      return;
    }
    this.saving.set(true);
    this.error.set('');
    this.moduleSvc.update(this.item.id, {
      title: this.title.trim(),
      description: this.description.trim() || null,
      cefrLevel: this.cefrLevel.trim() || null,
      skill: this.skill.trim() || null,
      subskill: this.subskill.trim() || null,
      contextTags: this.parseTags(this.contextTagsDraft),
      focusTags: this.parseTags(this.focusTagsDraft),
      difficultyBand: this.difficultyBand,
      estimatedMinutes: this.estimatedMinutes,
    }).subscribe({
      next: updated => {
        this.saving.set(false);
        this.router.navigateByUrl(`/admin/modules/${updated.id}`);
      },
      error: err => { this.saving.set(false); this.error.set(err.error?.error ?? 'Could not save changes.'); },
    });
  }
}
