import { Component, OnInit, ViewChild, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { AdminModuleService } from '../../../core/services/admin-module.service';
import {
  ModuleDto,
  ModulePreviewResult,
  ModulePreviewSubmitResult,
} from '../../../core/models/admin-module.models';
import { DiagnosticIssue } from '../../../core/models/admin-repair.models';
import { FormioRendererComponent } from '../../../shared/formio/formio-renderer.component';
import {
  SpAdminAlertComponent,
  SpAdminBadgeComponent,
  SpAdminButtonComponent,
  SpAdminErrorStateComponent,
  SpAdminFormFieldComponent,
  SpAdminLoadingStateComponent,
  SpAdminModalComponent,
  SpAdminPageBodyComponent,
  SpAdminPageHeaderComponent,
  SpAdminSectionCardComponent,
  SpAdminTextareaComponent,
} from '../../../design-system/admin';

/**
 * Phase K4 — Module detail as its own routed page (/admin/modules/:id), replacing the old
 * in-place slide-in drawer. Approve/Reject/Preview as Learner all live here now.
 *
 * Phase K5 — Edit moved to its own routed page (/admin/modules/:id/edit); Modules are now always
 * auto-generated by the Module auto-link flow, so hand-correction is the only way to fix a
 * title/description/tags after the fact.
 */
@Component({
  selector: 'app-admin-module-detail',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    SpAdminAlertComponent,
    SpAdminBadgeComponent,
    SpAdminButtonComponent,
    SpAdminErrorStateComponent,
    SpAdminFormFieldComponent,
    SpAdminLoadingStateComponent,
    SpAdminModalComponent,
    SpAdminPageBodyComponent,
    SpAdminPageHeaderComponent,
    SpAdminSectionCardComponent,
    SpAdminTextareaComponent,
    FormioRendererComponent,
  ],
  templateUrl: './admin-module-detail.component.html',
})
export class AdminModuleDetailComponent implements OnInit {
  itemId = '';
  item = signal<ModuleDto | null>(null);
  loading = signal(true);
  error = signal('');
  actionError = signal('');
  actionSuccess = signal('');
  rejectReasonDraft = '';
  approving = signal(false);
  rejecting = signal(false);
  archiving = signal(false);

  // ── Phase J3 — Preview as Learner modal ─────────────────────────────────
  previewModalOpen = signal(false);
  previewLoading = signal(false);
  previewError = signal('');
  previewData = signal<ModulePreviewResult | null>(null);
  previewSchema = signal<any>(null);
  previewSubmitting = signal(false);
  previewResult = signal<ModulePreviewSubmitResult | null>(null);
  // Sprint 10 — which linked Exercise (by index into previewData().exercises) is currently shown
  // in the preview modal, when a Module has more than one.
  selectedExerciseIndex = signal(0);
  selectedExercise = computed(() => this.previewData()?.exercises?.[this.selectedExerciseIndex()] ?? null);

  @ViewChild(FormioRendererComponent) previewFormioRenderer?: FormioRendererComponent;

  // ── Phase K8 — "Fix with AI" repair ──────────────────────────────────────
  issues = signal<DiagnosticIssue[]>([]);
  repairing = signal(false);
  repairSuccess = signal('');
  repairError = signal('');

  constructor(
    private moduleSvc: AdminModuleService,
    private route: ActivatedRoute,
    private router: Router,
  ) {}

  ngOnInit(): void {
    this.itemId = this.route.snapshot.paramMap.get('id') ?? '';
    if (!this.itemId) return;
    this.load();
  }

  load(): void {
    this.loading.set(true);
    this.error.set('');
    this.moduleSvc.get(this.itemId).subscribe({
      next: item => { this.item.set(item); this.loading.set(false); this.rejectReasonDraft = ''; },
      error: err => { this.loading.set(false); this.error.set(err.error?.error ?? 'Could not load this Module.'); },
    });
    this.moduleSvc.diagnose(this.itemId).subscribe({
      next: issues => this.issues.set(issues),
      error: () => this.issues.set([]),
    });
  }

  get autoFixableIssues(): DiagnosticIssue[] {
    return this.issues().filter(i => i.autoFixable);
  }

  fixWithAi(): void {
    this.repairing.set(true);
    this.repairError.set('');
    this.repairSuccess.set('');
    this.moduleSvc.repair(this.itemId).subscribe({
      next: result => {
        this.repairing.set(false);
        this.repairSuccess.set(`Fixed ${result.issuesFixed.length} issue(s)` + (result.providerName ? ` using ${result.providerName}/${result.modelName}.` : '.'));
        this.load();
      },
      error: err => { this.repairing.set(false); this.repairError.set(err.error?.error ?? 'Could not repair this Module.'); },
    });
  }

  backToList(): void {
    this.router.navigateByUrl('/admin/modules');
  }

  /** Sprint 10 — ContextTagsJson/FocusTagsJson were present in the API response but never bound
   * in this template at all. */
  parseTags(json: string | null | undefined): string[] {
    if (!json) return [];
    try {
      const parsed = JSON.parse(json);
      return Array.isArray(parsed) ? parsed.filter(t => typeof t === 'string') : [];
    } catch {
      return [];
    }
  }

  statusTone(status: string): 'success' | 'neutral' | 'danger' | 'warning' {
    if (status === 'Approved') return 'success';
    if (status === 'Rejected') return 'danger';
    if (status === 'PendingReview') return 'warning';
    return 'neutral';
  }

  approveSelected(): void {
    const item = this.item();
    if (!item) return;
    this.approving.set(true);
    this.actionError.set('');
    this.moduleSvc.approve(item.id).subscribe({
      next: updated => {
        this.approving.set(false);
        this.item.set(updated);
        this.actionSuccess.set('Module approved.');
      },
      error: err => { this.approving.set(false); this.actionError.set(err.error?.error ?? 'Could not approve.'); },
    });
  }

  rejectSelected(): void {
    const item = this.item();
    if (!item) return;
    if (!this.rejectReasonDraft.trim()) {
      this.actionError.set('A rejection reason is required.');
      return;
    }
    this.rejecting.set(true);
    this.actionError.set('');
    this.moduleSvc.reject(item.id, this.rejectReasonDraft.trim()).subscribe({
      next: updated => {
        this.rejecting.set(false);
        this.item.set(updated);
        this.actionSuccess.set('Module rejected.');
      },
      error: err => { this.rejecting.set(false); this.actionError.set(err.error?.error ?? 'Could not reject.'); },
    });
  }

  goToEdit(): void {
    this.router.navigateByUrl(`/admin/modules/${this.itemId}/edit`);
  }

  deleteItem(): void {
    this.archiving.set(true);
    this.actionError.set('');
    this.moduleSvc.archive([this.itemId]).subscribe({
      next: () => { this.archiving.set(false); this.backToList(); },
      error: err => { this.archiving.set(false); this.actionError.set(err.error?.error ?? 'Could not delete this Module.'); },
    });
  }

  restoreItem(): void {
    this.archiving.set(true);
    this.actionError.set('');
    this.moduleSvc.unarchive([this.itemId]).subscribe({
      next: () => { this.archiving.set(false); this.load(); },
      error: err => { this.archiving.set(false); this.actionError.set(err.error?.error ?? 'Could not restore this Module.'); },
    });
  }

  openPreview(): void {
    const item = this.item();
    if (!item) return;
    this.previewLoading.set(true);
    this.previewError.set('');
    this.previewData.set(null);
    this.previewSchema.set(null);
    this.previewResult.set(null);
    this.selectedExerciseIndex.set(0);
    this.previewModalOpen.set(true);

    this.moduleSvc.preview(item.id).subscribe({
      next: result => {
        this.previewLoading.set(false);
        this.previewData.set(result);
        this.loadSchemaForSelectedExercise();
      },
      error: err => {
        this.previewLoading.set(false);
        this.previewError.set(err.error?.error ?? 'Could not load the preview.');
      },
    });
  }

  closePreview(): void {
    this.previewModalOpen.set(false);
  }

  /** Sprint 10 — switches the preview modal to a different linked Exercise (previously the modal
   * could only ever show the first-linked Exercise, with no way to reach the rest). */
  selectExercise(index: number): void {
    this.selectedExerciseIndex.set(index);
    this.previewResult.set(null);
    this.previewError.set('');
    this.loadSchemaForSelectedExercise();
  }

  private loadSchemaForSelectedExercise(): void {
    const schemaJson = this.selectedExercise()?.formSchemaJson;
    if (!schemaJson) {
      this.previewSchema.set(null);
      return;
    }
    try {
      this.previewSchema.set(JSON.parse(schemaJson));
    } catch {
      this.previewSchema.set(null);
    }
  }

  submitPreviewAnswer(): void {
    this.previewFormioRenderer?.submitForm();
  }

  onPreviewExerciseSubmit(answers: Record<string, unknown>): void {
    const module = this.previewData();
    const exercise = this.selectedExercise();
    if (!module || !exercise) return;

    this.previewSubmitting.set(true);
    this.previewError.set('');
    this.moduleSvc.previewSubmit(module.moduleId, { answers, exerciseId: exercise.exerciseId }).subscribe({
      next: result => {
        this.previewSubmitting.set(false);
        this.previewResult.set(result);
      },
      error: err => {
        this.previewSubmitting.set(false);
        this.previewError.set(err.error?.error ?? 'Could not score the preview submission.');
      },
    });
  }
}
