using LinguaCoach.Domain.Common;

namespace LinguaCoach.Domain.Entities;

/// <summary>
/// A student's personalized learning path generated by AI at onboarding completion.
/// One active path per student at a time. Modules are ordered sequences of activities.
/// </summary>
public sealed class LearningPath : BaseEntity
{
    public Guid StudentProfileId { get; private set; }

    // Human-readable name, e.g. "Workplace English for Document Controllers — B1"
    public string Title { get; private set; }

    // AI summary of learner context used to generate this path.
    public string LearnerContextSummary { get; private set; }

    // Whether this is the student's currently active path.
    public bool IsActive { get; private set; }

    public IReadOnlyList<LearningModule> Modules => _modules.AsReadOnly();
    private readonly List<LearningModule> _modules = [];

    private LearningPath()
    {
        Title = string.Empty;
        LearnerContextSummary = string.Empty;
    }

    public LearningPath(Guid studentProfileId, string title, string learnerContextSummary)
    {
        if (studentProfileId == Guid.Empty) throw new ArgumentException("StudentProfileId must not be empty.", nameof(studentProfileId));
        if (string.IsNullOrWhiteSpace(title)) throw new ArgumentException("Title is required.", nameof(title));

        StudentProfileId = studentProfileId;
        Title = title.Trim();
        LearnerContextSummary = learnerContextSummary?.Trim() ?? string.Empty;
        IsActive = true;
    }

    public void Deactivate() => IsActive = false;
}
