using LinguaCoach.Domain.Common;
using LinguaCoach.Domain.ValueObjects;

namespace LinguaCoach.Domain.Entities;

/// <summary>
/// Compact rolling summary of a student's recent learning state.
/// Injected into every AI context packet instead of sending full history.
/// Updated after each lesson — never re-generated by AI.
/// Max 200 chars per summary field to enforce token budget discipline.
/// </summary>
public sealed class UserLearningSummary : BaseEntity
{
    public const int MaxSummaryLength = 200;
    private const int MaxStrongSkills = 10;
    private const int MaxWeakSkills = 10;
    private const int MaxRecurringMistakes = 10;
    private const int MaxCoveredScenarios = 20;
    private const int MaxNextFocus = 5;

    public Guid StudentProfileId { get; private set; }

    public string RecentWeaknesses { get; private set; }
    public string RecentProgress { get; private set; }
    public string? JourneySummary { get; private set; }
    public string StrongSkillsJson { get; private set; }
    public string WeakSkillsJson { get; private set; }
    public string RecurringMistakesJson { get; private set; }
    public string CoveredScenariosJson { get; private set; }
    public string NextFocusJson { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    private UserLearningSummary()
    {
        RecentWeaknesses = string.Empty;
        RecentProgress = string.Empty;
        StrongSkillsJson = "[]";
        WeakSkillsJson = "[]";
        RecurringMistakesJson = "[]";
        CoveredScenariosJson = "[]";
        NextFocusJson = "[]";
    }

    public UserLearningSummary(Guid studentProfileId)
    {
        if (studentProfileId == Guid.Empty) throw new ArgumentException("StudentProfileId must not be empty.", nameof(studentProfileId));
        StudentProfileId = studentProfileId;
        RecentWeaknesses = string.Empty;
        RecentProgress = string.Empty;
        StrongSkillsJson = "[]";
        WeakSkillsJson = "[]";
        RecurringMistakesJson = "[]";
        CoveredScenariosJson = "[]";
        NextFocusJson = "[]";
        UpdatedAt = DateTime.UtcNow;
    }

    public void Update(string recentWeaknesses, string recentProgress)
    {
        if (recentWeaknesses?.Length > MaxSummaryLength)
            throw new ArgumentException($"RecentWeaknesses must be at most {MaxSummaryLength} characters.", nameof(recentWeaknesses));
        if (recentProgress?.Length > MaxSummaryLength)
            throw new ArgumentException($"RecentProgress must be at most {MaxSummaryLength} characters.", nameof(recentProgress));

        RecentWeaknesses = recentWeaknesses?.Trim() ?? string.Empty;
        RecentProgress = recentProgress?.Trim() ?? string.Empty;
        UpdatedAt = DateTime.UtcNow;
    }

    public void ApplyDelta(MemoryUpdateDelta delta)
    {
        if (!string.IsNullOrWhiteSpace(delta.JourneySummaryDelta))
        {
            var current = JourneySummary?.Trim();
            var next = string.IsNullOrWhiteSpace(current)
                ? delta.JourneySummaryDelta.Trim()
                : $"{current} {delta.JourneySummaryDelta.Trim()}";
            JourneySummary = next.Length <= 1000 ? next : next[^1000..];
        }

        StrongSkillsJson = JsonStringList.Merge(StrongSkillsJson, delta.NewStrengths, MaxStrongSkills);
        WeakSkillsJson = JsonStringList.Merge(WeakSkillsJson, delta.NewWeaknesses, MaxWeakSkills);
        RecurringMistakesJson = JsonStringList.Merge(RecurringMistakesJson, delta.RecurringMistakesToAdd, MaxRecurringMistakes);
        CoveredScenariosJson = JsonStringList.Merge(CoveredScenariosJson, delta.CoveredScenariosToAdd, MaxCoveredScenarios);
        NextFocusJson = JsonStringList.Replace(delta.RecommendedNextFocus, MaxNextFocus);
        UpdatedAt = DateTime.UtcNow;
    }
}
