using LinguaCoach.Domain.Common;

namespace LinguaCoach.Domain.Entities;

/// <summary>
/// Compact rolling summary of a student's recent learning state.
/// Injected into every AI context packet instead of sending full history.
/// Updated after each lesson — never re-generated by AI.
/// Max 200 chars per summary field to enforce token budget discipline.
/// </summary>
public sealed class UserLearningSummary : BaseEntity
{
    public const int MaxSummaryLength = 200;

    public Guid StudentProfileId { get; private set; }

    public string RecentWeaknesses { get; private set; }
    public string RecentProgress { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    private UserLearningSummary() { RecentWeaknesses = string.Empty; RecentProgress = string.Empty; }

    public UserLearningSummary(Guid studentProfileId)
    {
        if (studentProfileId == Guid.Empty) throw new ArgumentException("StudentProfileId must not be empty.", nameof(studentProfileId));
        StudentProfileId = studentProfileId;
        RecentWeaknesses = string.Empty;
        RecentProgress = string.Empty;
        UpdatedAt = DateTime.UtcNow;
    }

    public void Update(string recentWeaknesses, string recentProgress)
    {
        if (recentWeaknesses?.Length > MaxSummaryLength)
            throw new ArgumentException($"RecentWeaknesses must be at most {MaxSummaryLength} characters.", nameof(recentWeaknesses));
        if (recentProgress?.Length > MaxSummaryLength)
            throw new ArgumentException($"RecentProgress must be at most {MaxSummaryLength} characters.", nameof(recentProgress));

        RecentWeaknesses = recentWeaknesses?.Trim() ?? string.Empty;
        RecentProgress = recentProgress?.Trim() ?? string.Empty;
        UpdatedAt = DateTime.UtcNow;
    }
}
