// <auto-generated />
using System;
using LinguaCoach.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinguaCoach.Persistence.Migrations
{
    [DbContext(typeof(LinguaCoachDbContext))]
    [Migration("20260601205257_T3_VocabularyAndSpeakingSchema")]
    partial class T3_VocabularyAndSpeakingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinguaCoach.Domain.Entities.AiPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<int?>("MaxInputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_input_tokens");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_output_tokens");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_prompts_key_version");

                    b.ToTable("ai_prompts", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.AiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId")
                        .HasDatabaseName("ix_ai_usage_logs_student_profile_id");

                    b.HasIndex("StudentProfileId", "CreatedAt")
                        .HasDatabaseName("ix_ai_usage_logs_student_profile_id_created_at");

                    b.ToTable("ai_usage_logs", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.CareerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LanguagePairId")
                        .HasDatabaseName("ix_career_profiles_language_pair_id");

                    b.ToTable("career_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Role-specific English for document control professionals in construction and engineering projects.",
                            LanguagePairId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Document Controller"
                        });
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.CurriculumWordList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("career_profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition");

                    b.Property<string>("ExampleSentence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("example_sentence");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tags");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("LanguagePairId");

                    b.HasIndex("CareerProfileId", "LanguagePairId", "Priority")
                        .HasDatabaseName("ix_curriculum_word_lists_career_lang_priority");

                    b.ToTable("curriculum_word_lists", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_code");

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "fa",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = 1,
                            Name = "Persian"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "en",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = 0,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LanguagePair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SourceLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_language_id");

                    b.Property<Guid>("TargetLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_language_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetLanguageId")
                        .HasDatabaseName("ix_language_pairs_target_language_id");

                    b.HasIndex("SourceLanguageId", "TargetLanguageId")
                        .IsUnique()
                        .HasDatabaseName("ix_language_pairs_source_target");

                    b.ToTable("language_pairs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            SourceLanguageId = new Guid("10000000-0000-0000-0000-000000000001"),
                            TargetLanguageId = new Guid("10000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LanguagePairId")
                        .HasDatabaseName("ix_learning_tracks_language_pair_id");

                    b.ToTable("learning_tracks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Role-specific English for professional workplace communication.",
                            LanguagePairId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Workplace English"
                        });
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.SpeakingScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("career_profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("goal");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("integer")
                        .HasColumnName("max_turns");

                    b.Property<string>("Rubric")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rubric");

                    b.Property<string>("TargetPhrases")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_phrases");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("LanguagePairId");

                    b.HasIndex("CareerProfileId", "LanguagePairId")
                        .HasDatabaseName("ix_speaking_scenarios_career_lang");

                    b.ToTable("speaking_scenarios", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.SpeakingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CareerContext")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("career_context");

                    b.Property<string>("CefrLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cefr_level");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("integer")
                        .HasColumnName("current_turn");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("integer")
                        .HasColumnName("max_turns");

                    b.Property<double?>("OverallScore")
                        .HasColumnType("double precision")
                        .HasColumnName("overall_score");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<string>("SessionSummary")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("session_summary");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId")
                        .HasDatabaseName("ix_speaking_sessions_scenario_id");

                    b.HasIndex("StudentProfileId", "Status")
                        .HasDatabaseName("ix_speaking_sessions_student_status");

                    b.ToTable("speaking_sessions", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.SpeakingTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiQuestion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_question");

                    b.Property<string>("AiReply")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_reply");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FeedbackJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("feedback_json");

                    b.Property<double?>("FluencyScore")
                        .HasColumnType("double precision")
                        .HasColumnName("fluency_score");

                    b.Property<double?>("GrammarScore")
                        .HasColumnType("double precision")
                        .HasColumnName("grammar_score");

                    b.Property<string>("MistakesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("mistakes_json");

                    b.Property<double?>("PronunciationScore")
                        .HasColumnType("double precision")
                        .HasColumnName("pronunciation_score");

                    b.Property<Guid>("SpeakingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("speaking_session_id");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.Property<string>("TurnSummary")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("turn_summary");

                    b.Property<string>("UserAudioUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_audio_url");

                    b.Property<string>("UserTranscript")
                        .HasColumnType("text")
                        .HasColumnName("user_transcript");

                    b.Property<double?>("VocabularyScore")
                        .HasColumnType("double precision")
                        .HasColumnName("vocabulary_score");

                    b.HasKey("Id");

                    b.HasIndex("SpeakingSessionId", "TurnNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_speaking_turns_session_turn");

                    b.ToTable("speaking_turns", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CareerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("career_profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<int>("LastCompletedStep")
                        .HasColumnType("integer")
                        .HasColumnName("last_completed_step");

                    b.Property<Guid?>("LearningTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("learning_track_id");

                    b.Property<int>("OnboardingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("onboarding_status");

                    b.Property<int?>("SkillFocus")
                        .HasColumnType("integer")
                        .HasColumnName("skill_focus");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CareerProfileId")
                        .HasDatabaseName("ix_student_profiles_career_profile_id");

                    b.HasIndex("LanguagePairId")
                        .HasDatabaseName("ix_student_profiles_language_pair_id");

                    b.HasIndex("LearningTrackId")
                        .HasDatabaseName("ix_student_profiles_learning_track_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_profiles_user_id");

                    b.HasIndex("UserId", "OnboardingStatus")
                        .HasDatabaseName("ix_student_profiles_user_id_onboarding_status");

                    b.ToTable("student_profiles", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.UserLearningSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RecentProgress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recent_progress");

                    b.Property<string>("RecentWeaknesses")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recent_weaknesses");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_learning_summaries_student_profile_id");

                    b.ToTable("user_learning_summaries", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.VocabularyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("ease_factor");

                    b.Property<int>("ExposureCount")
                        .HasColumnType("integer")
                        .HasColumnName("exposure_count");

                    b.Property<int>("IncorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("incorrect_count");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<DateTime?>("LastPractised")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_practised");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<double>("MasteryScore")
                        .HasColumnType("double precision")
                        .HasColumnName("mastery_score");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_review_date");

                    b.Property<int>("RecallCount")
                        .HasColumnType("integer")
                        .HasColumnName("recall_count");

                    b.Property<int>("RecognitionCount")
                        .HasColumnType("integer")
                        .HasColumnName("recognition_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("LanguagePairId");

                    b.HasIndex("StudentProfileId", "LanguagePairId")
                        .HasDatabaseName("ix_vocabulary_entries_student_lang");

                    b.HasIndex("StudentProfileId", "NextReviewDate")
                        .HasDatabaseName("ix_vocabulary_entries_student_next_review");

                    b.HasIndex("StudentProfileId", "Status")
                        .HasDatabaseName("ix_vocabulary_entries_student_status");

                    b.ToTable("vocabulary_entries", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.AiUsageLog", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.CareerProfile", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", "LanguagePair")
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LanguagePair");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.CurriculumWordList", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.CareerProfile", null)
                        .WithMany()
                        .HasForeignKey("CareerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", null)
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LanguagePair", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.Language", "SourceLanguage")
                        .WithMany()
                        .HasForeignKey("SourceLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.Language", "TargetLanguage")
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceLanguage");

                    b.Navigation("TargetLanguage");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningTrack", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", "LanguagePair")
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LanguagePair");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.SpeakingScenario", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.CareerProfile", null)
                        .WithMany()
                        .HasForeignKey("CareerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", null)
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.SpeakingSession", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.SpeakingScenario", null)
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.SpeakingTurn", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.SpeakingSession", null)
                        .WithMany()
                        .HasForeignKey("SpeakingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.CareerProfile", "CareerProfile")
                        .WithMany()
                        .HasForeignKey("CareerProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", "LanguagePair")
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LinguaCoach.Domain.Entities.LearningTrack", "LearningTrack")
                        .WithMany()
                        .HasForeignKey("LearningTrackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CareerProfile");

                    b.Navigation("LanguagePair");

                    b.Navigation("LearningTrack");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.UserLearningSummary", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.VocabularyEntry", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", null)
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
