// <auto-generated />
using System;
using LinguaCoach.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinguaCoach.Persistence.Migrations
{
    [DbContext(typeof(LinguaCoachDbContext))]
    [Migration("20260604234848_T20_AiUsageLogEnrichment")]
    partial class T20_AiUsageLogEnrichment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinguaCoach.Domain.Entities.ActivityAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("audio_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FeedbackJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("feedback_json");

                    b.Property<Guid>("LearningActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("learning_activity_id");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("prompt_key");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<string>("SubmittedContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submitted_content");

                    b.HasKey("Id");

                    b.HasIndex("LearningActivityId")
                        .HasDatabaseName("ix_activity_attempts_activity");

                    b.HasIndex("StudentProfileId")
                        .HasDatabaseName("ix_activity_attempts_student");

                    b.ToTable("activity_attempts", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.AiPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<int?>("MaxInputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_input_tokens");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_output_tokens");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_prompts_key_version");

                    b.ToTable("ai_prompts", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.AiProviderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("FallbackEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fallback_enabled");

                    b.Property<string>("FallbackModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fallback_model_name");

                    b.Property<string>("FallbackProviderName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fallback_provider_name");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("feature_key");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FeatureKey")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_provider_configs_feature_key");

                    b.ToTable("ai_provider_configs", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.AiProviderCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModelTests")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_tests");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_provider_credentials_provider_name");

                    b.ToTable("ai_provider_credentials", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.AiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("correlation_id");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("feature_key");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fallback");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<Guid?>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("boolean")
                        .HasColumnName("was_successful");

                    b.HasKey("Id");

                    b.HasIndex("FeatureKey")
                        .HasDatabaseName("ix_ai_usage_logs_feature_key");

                    b.HasIndex("ProviderName")
                        .HasDatabaseName("ix_ai_usage_logs_provider_name");

                    b.HasIndex("StudentProfileId")
                        .HasDatabaseName("ix_ai_usage_logs_student_profile_id");

                    b.HasIndex("StudentProfileId", "CreatedAt")
                        .HasDatabaseName("ix_ai_usage_logs_student_profile_id_created_at");

                    b.ToTable("ai_usage_logs", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.CareerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LanguagePairId")
                        .HasDatabaseName("ix_career_profiles_language_pair_id");

                    b.ToTable("career_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Role-specific English for document control professionals in construction and engineering projects.",
                            LanguagePairId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Document Controller"
                        });
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.CurriculumWordList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("career_profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition");

                    b.Property<string>("ExampleSentence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("example_sentence");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tags");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("LanguagePairId");

                    b.HasIndex("CareerProfileId", "LanguagePairId", "Priority")
                        .HasDatabaseName("ix_curriculum_word_lists_career_lang_priority");

                    b.ToTable("curriculum_word_lists", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_code");

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "fa",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = 1,
                            Name = "Persian"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "en",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = 0,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LanguagePair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SourceLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_language_id");

                    b.Property<Guid>("TargetLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_language_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetLanguageId")
                        .HasDatabaseName("ix_language_pairs_target_language_id");

                    b.HasIndex("SourceLanguageId", "TargetLanguageId")
                        .IsUnique()
                        .HasDatabaseName("ix_language_pairs_source_target");

                    b.ToTable("language_pairs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            SourceLanguageId = new Guid("10000000-0000-0000-0000-000000000001"),
                            TargetLanguageId = new Guid("10000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActivityType")
                        .HasColumnType("integer")
                        .HasColumnName("activity_type");

                    b.Property<string>("AiGeneratedContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_generated_content_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("LearningModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("learning_module_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceWritingScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_writing_scenario_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("LearningModuleId");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_learning_activities_source");

                    b.HasIndex("ActivityType", "IsActive")
                        .HasDatabaseName("ix_learning_activities_type_active")
                        .HasFilter("is_active = true");

                    b.ToTable("learning_activities", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LearningPathId")
                        .HasColumnType("uuid")
                        .HasColumnName("learning_path_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("LearningPathId", "Order")
                        .HasDatabaseName("ix_learning_modules_path_order");

                    b.ToTable("learning_modules", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LearnerContextSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("learner_context_summary");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId", "IsActive")
                        .HasDatabaseName("ix_learning_paths_student_active");

                    b.ToTable("learning_paths", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LanguagePairId")
                        .HasDatabaseName("ix_learning_tracks_language_pair_id");

                    b.ToTable("learning_tracks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Role-specific English for professional workplace communication.",
                            LanguagePairId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Workplace English"
                        });
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LessonVocabularyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("LessonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_number");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<Guid>("VocabularyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_entry_id");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyEntryId");

                    b.HasIndex("StudentProfileId", "LessonNumber")
                        .HasDatabaseName("ix_lesson_vocabulary_logs_student_lesson");

                    b.HasIndex("StudentProfileId", "OccurredAt")
                        .HasDatabaseName("ix_lesson_vocabulary_logs_student_occurred");

                    b.ToTable("lesson_vocabulary_logs", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.SpeakingScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("career_profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("goal");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("integer")
                        .HasColumnName("max_turns");

                    b.Property<string>("Rubric")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rubric");

                    b.Property<string>("TargetPhrases")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_phrases");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("LanguagePairId");

                    b.HasIndex("CareerProfileId", "LanguagePairId")
                        .HasDatabaseName("ix_speaking_scenarios_career_lang");

                    b.ToTable("speaking_scenarios", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.SpeakingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CareerContext")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("career_context");

                    b.Property<string>("CefrLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cefr_level");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("integer")
                        .HasColumnName("current_turn");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("integer")
                        .HasColumnName("max_turns");

                    b.Property<double?>("OverallScore")
                        .HasColumnType("double precision")
                        .HasColumnName("overall_score");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<string>("SessionSummary")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("session_summary");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId")
                        .HasDatabaseName("ix_speaking_sessions_scenario_id");

                    b.HasIndex("StudentProfileId", "Status")
                        .HasDatabaseName("ix_speaking_sessions_student_status");

                    b.ToTable("speaking_sessions", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.SpeakingTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiQuestion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_question");

                    b.Property<string>("AiReply")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_reply");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FeedbackJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("feedback_json");

                    b.Property<double?>("FluencyScore")
                        .HasColumnType("double precision")
                        .HasColumnName("fluency_score");

                    b.Property<double?>("GrammarScore")
                        .HasColumnType("double precision")
                        .HasColumnName("grammar_score");

                    b.Property<string>("MistakesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("mistakes_json");

                    b.Property<double?>("PronunciationScore")
                        .HasColumnType("double precision")
                        .HasColumnName("pronunciation_score");

                    b.Property<Guid>("SpeakingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("speaking_session_id");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.Property<string>("TurnSummary")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("turn_summary");

                    b.Property<string>("UserAudioUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_audio_url");

                    b.Property<string>("UserTranscript")
                        .HasColumnType("text")
                        .HasColumnName("user_transcript");

                    b.Property<double?>("VocabularyScore")
                        .HasColumnType("double precision")
                        .HasColumnName("vocabulary_score");

                    b.HasKey("Id");

                    b.HasIndex("SpeakingSessionId", "TurnNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_speaking_turns_session_turn");

                    b.ToTable("speaking_turns", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CareerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("career_profile_id");

                    b.Property<string>("CefrLevel")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("cefr_level");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<int>("LastCompletedStep")
                        .HasColumnType("integer")
                        .HasColumnName("last_completed_step");

                    b.Property<Guid?>("LearningTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("learning_track_id");

                    b.Property<int>("OnboardingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("onboarding_status");

                    b.Property<int?>("SkillFocus")
                        .HasColumnType("integer")
                        .HasColumnName("skill_focus");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CareerProfileId")
                        .HasDatabaseName("ix_student_profiles_career_profile_id");

                    b.HasIndex("LanguagePairId")
                        .HasDatabaseName("ix_student_profiles_language_pair_id");

                    b.HasIndex("LearningTrackId")
                        .HasDatabaseName("ix_student_profiles_learning_track_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_profiles_user_id");

                    b.HasIndex("UserId", "OnboardingStatus")
                        .HasDatabaseName("ix_student_profiles_user_id_onboarding_status");

                    b.ToTable("student_profiles", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.UserLearningSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RecentProgress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recent_progress");

                    b.Property<string>("RecentWeaknesses")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recent_weaknesses");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_learning_summaries_student_profile_id");

                    b.ToTable("user_learning_summaries", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.VocabularyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("ease_factor");

                    b.Property<int>("ExposureCount")
                        .HasColumnType("integer")
                        .HasColumnName("exposure_count");

                    b.Property<int>("IncorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("incorrect_count");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<DateTime?>("LastPractised")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_practised");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<double>("MasteryScore")
                        .HasColumnType("double precision")
                        .HasColumnName("mastery_score");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_review_date");

                    b.Property<int>("RecallCount")
                        .HasColumnType("integer")
                        .HasColumnName("recall_count");

                    b.Property<int>("RecognitionCount")
                        .HasColumnType("integer")
                        .HasColumnName("recognition_count");

                    b.Property<int>("RepetitionCount")
                        .HasColumnType("integer")
                        .HasColumnName("repetition_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("LanguagePairId");

                    b.HasIndex("StudentProfileId", "LanguagePairId")
                        .HasDatabaseName("ix_vocabulary_entries_student_lang");

                    b.HasIndex("StudentProfileId", "NextReviewDate")
                        .HasDatabaseName("ix_vocabulary_entries_student_next_review");

                    b.HasIndex("StudentProfileId", "Status")
                        .HasDatabaseName("ix_vocabulary_entries_student_status");

                    b.ToTable("vocabulary_entries", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.WritingScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CareerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("career_profile_id");

                    b.Property<string>("CommonMistakeToAvoid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("common_mistake_to_avoid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("difficulty");

                    b.Property<string>("ExampleText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("example_text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<string>("LearningGoal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("learning_goal");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("situation");

                    b.Property<string>("TargetPhrasesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("target_phrases_json");

                    b.Property<string>("TargetVocabularyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("target_vocabulary_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CareerProfileId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_writing_scenarios_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("LanguagePairId");

                    b.ToTable("writing_scenarios", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.WritingSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrectedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corrected_text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FeedbackJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("feedback_json");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_text");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("prompt_key");

                    b.Property<Guid?>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<string>("ScenarioTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("scenario_title");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("StudentProfileId", "CreatedAt")
                        .HasDatabaseName("ix_writing_submissions_student_created");

                    b.ToTable("writing_submissions", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Persistence.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.ActivityAttempt", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.LearningActivity", null)
                        .WithMany("Attempts")
                        .HasForeignKey("LearningActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.AiUsageLog", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.CareerProfile", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", "LanguagePair")
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LanguagePair");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.CurriculumWordList", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.CareerProfile", null)
                        .WithMany()
                        .HasForeignKey("CareerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", null)
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LanguagePair", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.Language", "SourceLanguage")
                        .WithMany()
                        .HasForeignKey("SourceLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.Language", "TargetLanguage")
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceLanguage");

                    b.Navigation("TargetLanguage");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningActivity", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.LearningModule", null)
                        .WithMany("Activities")
                        .HasForeignKey("LearningModuleId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningModule", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.LearningPath", null)
                        .WithMany("Modules")
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningPath", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningTrack", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", "LanguagePair")
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LanguagePair");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LessonVocabularyLog", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.VocabularyEntry", null)
                        .WithMany()
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.SpeakingScenario", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.CareerProfile", null)
                        .WithMany()
                        .HasForeignKey("CareerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", null)
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.SpeakingSession", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.SpeakingScenario", null)
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.SpeakingTurn", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.SpeakingSession", null)
                        .WithMany()
                        .HasForeignKey("SpeakingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.CareerProfile", "CareerProfile")
                        .WithMany()
                        .HasForeignKey("CareerProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", "LanguagePair")
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LinguaCoach.Domain.Entities.LearningTrack", "LearningTrack")
                        .WithMany()
                        .HasForeignKey("LearningTrackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CareerProfile");

                    b.Navigation("LanguagePair");

                    b.Navigation("LearningTrack");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.UserLearningSummary", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.VocabularyEntry", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", null)
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.WritingScenario", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.CareerProfile", null)
                        .WithMany()
                        .HasForeignKey("CareerProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", null)
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.WritingSubmission", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.WritingScenario", null)
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinguaCoach.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LinguaCoach.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LinguaCoach.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LinguaCoach.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningActivity", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningModule", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningPath", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
