// <auto-generated />
using LinguaCoach.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinguaCoach.Persistence.Migrations
{
    [DbContext(typeof(LinguaCoachDbContext))]
    [Migration("20260630150000_T67_WritingEvaluationTables")]
    partial class T67_WritingEvaluationTables
    {
    }
}
