// <auto-generated />
using LinguaCoach.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinguaCoach.Persistence.Migrations
{
    [DbContext(typeof(LinguaCoachDbContext))]
    [Migration("20260628120000_T65_SpeakingEvaluationFoundation")]
    partial class T65_SpeakingEvaluationFoundation
    {
    }
}
