// <auto-generated />
using System;
using LinguaCoach.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinguaCoach.Persistence.Migrations
{
    [DbContext(typeof(LinguaCoachDbContext))]
    partial class LinguaCoachDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinguaCoach.Domain.Entities.AiPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_prompts_key_version");

                    b.ToTable("ai_prompts", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.AiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId")
                        .HasDatabaseName("ix_ai_usage_logs_student_profile_id");

                    b.HasIndex("StudentProfileId", "CreatedAt")
                        .HasDatabaseName("ix_ai_usage_logs_student_profile_id_created_at");

                    b.ToTable("ai_usage_logs", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.CareerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LanguagePairId")
                        .HasDatabaseName("ix_career_profiles_language_pair_id");

                    b.ToTable("career_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Role-specific English for document control professionals in construction and engineering projects.",
                            LanguagePairId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Document Controller"
                        });
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_code");

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "fa",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = 1,
                            Name = "Persian"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "en",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = 0,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LanguagePair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SourceLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_language_id");

                    b.Property<Guid>("TargetLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_language_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetLanguageId");

                    b.HasIndex("SourceLanguageId", "TargetLanguageId")
                        .IsUnique()
                        .HasDatabaseName("ix_language_pairs_source_target");

                    b.ToTable("language_pairs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            SourceLanguageId = new Guid("10000000-0000-0000-0000-000000000001"),
                            TargetLanguageId = new Guid("10000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LanguagePairId")
                        .HasDatabaseName("ix_learning_tracks_language_pair_id");

                    b.ToTable("learning_tracks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Role-specific English for professional workplace communication.",
                            LanguagePairId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Workplace English"
                        });
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CareerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("career_profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<int>("LastCompletedStep")
                        .HasColumnType("integer")
                        .HasColumnName("last_completed_step");

                    b.Property<Guid?>("LearningTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("learning_track_id");

                    b.Property<int>("OnboardingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("onboarding_status");

                    b.Property<int?>("SkillFocus")
                        .HasColumnType("integer")
                        .HasColumnName("skill_focus");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CareerProfileId");

                    b.HasIndex("LanguagePairId");

                    b.HasIndex("LearningTrackId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_profiles_user_id");

                    b.HasIndex("UserId", "OnboardingStatus")
                        .HasDatabaseName("ix_student_profiles_user_id_onboarding_status");

                    b.ToTable("student_profiles", (string)null);
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.CareerProfile", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", "LanguagePair")
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LanguagePair");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LanguagePair", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.Language", "SourceLanguage")
                        .WithMany()
                        .HasForeignKey("SourceLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaCoach.Domain.Entities.Language", "TargetLanguage")
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceLanguage");

                    b.Navigation("TargetLanguage");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.LearningTrack", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", "LanguagePair")
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LanguagePair");
                });

            modelBuilder.Entity("LinguaCoach.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("LinguaCoach.Domain.Entities.CareerProfile", "CareerProfile")
                        .WithMany()
                        .HasForeignKey("CareerProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LinguaCoach.Domain.Entities.LanguagePair", "LanguagePair")
                        .WithMany()
                        .HasForeignKey("LanguagePairId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LinguaCoach.Domain.Entities.LearningTrack", "LearningTrack")
                        .WithMany()
                        .HasForeignKey("LearningTrackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CareerProfile");

                    b.Navigation("LanguagePair");

                    b.Navigation("LearningTrack");
                });
#pragma warning restore 612, 618
        }
    }
}
